In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

In [80]:
df = pd.read_csv('Datasets/elektronisk-rapportering-ers-2018-fangstmelding-dca-simple.csv', delimiter=';')

In [81]:
# Starttidspunkt og Stopptidspunkt inneholder både dato og klokkeslett. Dette gjør en del andre kolonner redunante.
# Vi kan også finne varighet ved Stopptidspunkt - Starttidspunkt
# Fangstår virker å være lik årstallet i Stopptidspunkt
# Kanskje vi burde beholde kolonner med koder og opprette dictionaries hvor vi kan slå opp tilhørende art/redskap

new_df = df.drop(columns = ['Meldingsdato', 'Meldingsklokkeslett', 'Startdato', 'Startklokkeslett', 'Hovedområde start (kode)', 'Stoppdato',
                            'Stoppklokkeslett', 'Varighet', 'Fangstår', 'Redskap FAO (kode)', 'Redskap FDIR (kode)', 'Hovedart FAO (kode)', 'Art FAO (kode)', 
                            'Art - FDIR (kode)', 'Art - gruppe (kode)', 'Lengdegruppe (kode)'] )

In [82]:
# Dropper en hel rad hvor en gitt kolonne inneholder en spesifikk verdi

#     df = df.drop(df[df['column_name'] == 'specific_value'].index)

# Hvis viktige felter ikke er fyllt ut, kan vi da stole på at resten av fangstmeldingen gir oss korrekt informasjon? 

# Dropper en hel rad hvor en gitt kolonne inneholder en nullverdi
new_df = new_df.dropna(subset = ['Hovedområde start'])

# dropna() kan brukes uten innsente argumenter for å fjerne rader med nullverdier
# Feltene for 'Bruttotonnasje 1969' og 'Bruttotonnasje annen' vil som regel ikke være fyllt ut samtidig.
# Derfor vil de fleste radene i tabellen inneholde minst én null-verdi

In [83]:
new_df['Starttidspunkt'] = pd.to_datetime(df['Starttidspunkt'])
new_df['Stopptidspunkt'] = pd.to_datetime(df['Stopptidspunkt'])
new_df['Meldingstidspunkt'] = pd.to_datetime(df['Meldingstidspunkt'])

In [85]:


new_df

,Melding ID,Meldingstidspunkt,Starttidspunkt,Startposisjon bredde,Startposisjon lengde,Hovedområde start,Lokasjon start (kode),Havdybde start,Stopptidspunkt,Stopposisjon bredde,...,Hovedart - FDIR (kode),Art FAO,Art - FDIR,Art - gruppe,Rundvekt,Lengdegruppe,Bruttotonnasje 1969,Bruttotonnasje annen,Bredde,Fartøylengde
1,1497178,2018-01-01 00:00:00,2017-12-30 23:21:00,"74,885","16,048",Bjørnøya,7.0,-335,2017-12-31 04:16:00,"74,914",...,1027.0,Hyse,Hyse,Hyse,9594.0,28 m og over,1476.0,NaN,"12,6","56,8"
2,1497178,2018-01-01 00:00:00,2017-12-30 23:21:00,"74,885","16,048",Bjørnøya,7.0,-335,2017-12-31 04:16:00,"74,914",...,1027.0,Torsk,Torsk,Torsk,8510.0,28 m og over,1476.0,NaN,"12,6","56,8"
3,1497178,2018-01-01 00:00:00,2017-12-30 23:21:00,"74,885","16,048",Bjørnøya,7.0,-335,2017-12-31 04:16:00,"74,914",...,1027.0,Blåkveite,Blåkveite,Blåkveite,196.0,28 m og over,1476.0,NaN,"12,6","56,8"
4,1497178,2018-01-01 00:00:00,2017-12-30 23:21:00,"74,885","16,048",Bjørnøya,7.0,-335,2017-12-31 04:16:00,"74,914",...,1027.0,Sei,Sei,Sei,134.0,28 m og over,1476.0,NaN,"12,6","56,8"
5,1497178,2018-01-01 00:00:00,2017-12-31 05:48:00,"74,91","15,868",Bjørnøya,7.0,-403,2017-12-31 10:15:00,"74,901",...,1027.0,Hyse,Hyse,Hyse,9118.0,28 m og over,1476.0,NaN,"12,6","56,8"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305429,1800291,2019-01-01 09:28:00,2018-12-31 19:41:00,"76,906","12,709",Vest-Spitsbergen,12.0,-349,2018-12-31 23:33:00,"77,091",...,1027.0,Gråsteinbit,Gråsteinbit,Steinbiter,145.0,28 m og over,1483.0,NaN,"12,6","57,3"
305430,1800291,2019-01-01 09:28:00,2018-12-31 19:41:00,"76,906","12,709",Vest-Spitsbergen,12.0,-349,2018-12-31 23:33:00,"77,091",...,1027.0,Uer (vanlig),Uer (vanlig),Uer,136.0,28 m og over,1483.0,NaN,"12,6","57,3"
305431,1800291,2019-01-01 09:28:00,2018-12-31 19:41:00,"76,906","12,709",Vest-Spitsbergen,12.0,-349,2018-12-31 23:33:00,"77,091",...,1027.0,Flekksteinbit,Flekksteinbit,Steinbiter,132.0,28 m og over,1483.0,NaN,"12,6","57,3"
305432,1800291,2019-01-01 09:28:00,2018-12-31 19:41:00,"76,906","12,709",Vest-Spitsbergen,12.0,-349,2018-12-31 23:33:00,"77,091",...,1027.0,Snabeluer,Snabeluer,Uer,102.0,28 m og over,1483.0,NaN,"12,6","57,3"
305433,1800291,2019-01-01 09:28:00,2018-12-31 19:41:00,"76,906","12,709",Vest-Spitsbergen,12.0,-349,2018-12-31 23:33:00,"77,091",...,1027.0,Blåkveite,Blåkveite,Blåkveite,63.0,28 m og over,1483.0,NaN,"12,6","57,3"